### ISSUE TITLE
Selected Icons not working

### ISSUE THREAD

**Issue by engmsaleh** [Ramotion/animated-tab-bar#134] opened 2016-09-06 18:44 UTC
When I use the tabbarcontroller programmatically and set both `normal` and `selected` images for `RAMAnimatedTabBarItem` .
The `selected` icons never displayed , only `normal` ones. 

`let tabBarItem2 = RAMAnimatedTabBarItem(title:"Facebook", image:UIImage(named:"750-home"), selectedImage: UIImage(named:"750-home-selected"))
`

**Comment by Kaelzs** [comment] 2016-09-08 06:24
sam  question, i used storyboard to set normal images and selected images, but it can only show the normal one, if i click the tab icon, it will change to an rectangle with pure color, 
![screenshot 2016-09-08 14 23 04](https://cloud.githubusercontent.com/assets/12252293/18339067/e18e52f6-75cf-11e6-8d10-f32bc9234cdf.png)
like this.

**Comment by engmsaleh** [comment] 2016-09-08 10:15
@Kaelzs I think it is an issue in the library. I ended up removing it and using apple `UITabbarController` and it worked corectly.

**Comment by engmsaleh** [comment] 2016-09-08 10:44
@Kaelzs I think it is an issue in the library. I ended up removing it and using apple `UITabbarController` and it worked corectly.

**Comment by Kaelzs** [comment] 2016-09-09 09:57
@engmsaleh I know, and i think it may be a solution to add an custom animation class for that, and i judge the icon.image if is equal to some custom image, i will set the image to it corresponding selected image

**Comment by cherishloveyou** [comment] 2016-09-26 08:54
strange! RAMAnimatedTabBarItem did not get UITabBarItem's Image

**Comment by ed-mejia** [comment] 2016-11-04 03:07
Having the same issue here. :(

**Comment by dudiaohanjiangxue** [comment] 2016-11-18 08:02
`selectedImage` can not work in RAMAnimatedYabBarController 

you can use `iconSelectedColor` to set what you want 
just like :
   `let item = RAMAnimatedTabBarItem(title: title, image: image, selectedImage: selecteImage) `
      `   let animation = RAMTransitionItemAnimations()`
     `   animation.iconSelectedColor = UIColor.orange`
        `animation.transitionOptions = UIViewAnimationOptions.transitionCurlUp`
       ` item.animation = animation`

**Comment by Kaelzs** [comment] 2016-11-22 05:09
@dudiaohanjiangxue 
that's easy, but the question is that we want change the button image not only for the color.
such as
![tab5](https://cloud.githubusercontent.com/assets/12252293/20511529/15bb3930-b0b4-11e6-8ceb-640e8e196146.png)
![tab6](https://cloud.githubusercontent.com/assets/12252293/20511530/16d4384e-b0b4-11e6-986f-9b757728b657.png)
this two image, can not convert by change icon selected color, and now my solution is to write my own animation class, and implement this 
``` swift
override public func playAnimation(icon: UIImageView, textLabel: UILabel) {
        for (id, image) in KYBounceAnimation.images.enumerate() {
            if icon.image?.isTheSameImage(withImage: image) == true {
                let newImage = KYBounceAnimation.selectedImages[id]
                self.playBounceAnimation(icon, withNewImage: newImage)
                textLabel.textColor = textSelectedColor
                return
            }
        }
        playBounceAnimation(icon, withNewImage: nil)
        textLabel.textColor = textSelectedColor
        
    }
```
and that's the only way i can think of to solve this problem, and i hope the author can fix this problem and support selected image.

**Comment by hrsalehi** [comment] 2016-12-31 11:01
can you please write a little more details? what is ```KYBounceAnimation``` class and how does ```playBounceAnimation``` work with ```newImage``` ?

**Comment by thecorsair** [comment] 2017-02-13 06:42
Thanks that was great

**Comment by Mohamed3amer** [comment] 2017-03-07 13:58
I fixed this issue as following:-

- Edit RAMAnimatedTabBarItem class by the following:
    1- add two properties
        var itemImage: UIImage?
        var itemSelectedImage: UIImage?
    2- add the following line at the beginning of playAnimation() function
        iconView?.icon.image = itemSelectedImage
    3- add the following line at the beginning of deselectAnimation() function
        iconView?.icon.image = itemImage
    4- add the following line at the beginning of selectedState() function
        iconView?.icon.image = itemSelectedImage
   
- Edit RAMAnimatedTabBarController class by the following:

  1- add the following lines in createCustomIcons function
        item.itemImage = item.image
        item.itemSelectedImage = item.selectedImage
**befor this block of code**
      if 0 == index { // selected first elemet
        item.selectedState()
        container.backgroundColor = (items as [RAMAnimatedTabBarItem])[index].bgSelectedColor
      }

**Comment by 1dividedby0** [comment] 2017-04-13 21:21
@Mohamed3amer could you submit this for the next pod version?

**Comment by ober01** [comment] 2018-04-16 12:37
Duplicate of #209

**Closed by ober01** 2018-04-16 12:37 UTC
