### ISSUE TITLE
In Xcode8 no animation outlet is showing on RAMAnimatedTabBarItem

### ISSUE THREAD

**Issue by helloniklas** [Ramotion/animated-tab-bar#142] opened 2016-10-21 15:21 UTC
Can't get the animation outlet to show up, despite following all the steps?

**Comment by towry** [comment] 2017-02-15 02:42
I have the save issue.

I use carthage to install the framework, and follow the usage steps, in the final step, can not create the connection between NSObject(RAMFumeAnimation) with RAMAnimatedTabBarItem.

![screen shot 2017-02-15 at 10 13 25 am](https://cloud.githubusercontent.com/assets/8279858/22958591/30d78ba2-f36b-11e6-97af-5e9f5bbd6e64.png)

My demo app is first created as single view app, then I convert it to tabbed application by embed in a tab controller.

**Comment by towry** [comment] 2017-02-15 03:29
I think this issue can be closed, see:

https://github.com/Carthage/Carthage/issues/763

**Comment by towry** [comment] 2017-02-15 05:32
Use pod instead of carthage is ok.

**Comment by ober01** [comment] 2018-04-16 13:05
Duplicate of #763

**Closed by ober01** 2018-04-16 13:05 UTC
