### ISSUE TITLE
hidesBottomBarWhenPushed don't work 

### ISSUE THREAD

**Issue by kaich** [Ramotion/animated-tab-bar#213] opened 2018-03-19 03:32 UTC
I use `hidesBottomBarWhenPushed = true `. But it doesn't work. I find your content is added to `View` of `UITabBarController`. And your custom container's height is 49. I think you can add container on tabbar. I change the source code as below.

```
    fileprivate func createViewContainer() -> UIView {
        let viewContainer = UIView()
        viewContainer.backgroundColor = UIColor.clear // for test
        viewContainer.translatesAutoresizingMaskIntoConstraints = false
        viewContainer.isExclusiveTouch = true
        tabBar.addSubview(viewContainer)
```

But new bug occurs.  Hope you  fix   hidesBottomBarWhenPushed bug

**Comment by xgoo** [comment] 2018-04-10 10:01
Me too...

**Comment by ober01** [comment] 2018-04-17 08:52
Duplicate of #144

**Closed by ober01** 2018-04-17 08:52 UTC
